# Generated by Django 6.1.1 on 2026-09-25 22:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_address_postal_code'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='last_updates',
            new_name='last_update',
        ),
    ]
